name: IBM DEBUG CI

on:
  push:
  #   branches: [ main ]
  # pull_request:

permissions:
  contents: read
  checks: write

jobs:
  ibm-ci:
    name: IBM CI
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        # Thanks to: https://github.com/IBM/actionspz
        # os: [ubuntu-24.04-ppc64le, ubuntu-24.04-s390x]
        os: [ubuntu-24.04-s390x]
        include:
          # - os: ubuntu-24.04-ppc64le
          #   arch: ppc64le
          - os: ubuntu-24.04-s390x
            arch: s390x
        # version: [11, 17, 21]
        version: [21]
    steps:
      - name: Debug
        run: |
          curl -L https://github.com/bytecodealliance/wasm-tools/releases/download/v1.227.1/wasm-tools-1.227.1-wasm32-wasip1.tar.gz -o wasm-tools-curl.tar.gz
          wget https://github.com/bytecodealliance/wasm-tools/releases/download/v1.227.1/wasm-tools-1.227.1-wasm32-wasip1.tar.gz
          ls -alh
